name: app_escola_ecoaprender
description: Aplicativo da Escola Eco Aprender.
version: 2.0.0+2

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: any # DI
  dio: any # HttpRequest
  intl: ^0.15.8 # Conversões de número
  shared_preferences: ^0.5.3 # Salvar no dispositivo
  onesignal_flutter: ^2.3.4 # Push Notification

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true